Double-check background maps were made

diff --git a/gleam_scripts/mosaics/queue/week_mosaic_array.template b/gleam_scripts/mosaics/queue/week_mosaic_array.template
--- a/gleam_scripts/mosaics/queue/week_mosaic_array.template
+++ b/gleam_scripts/mosaics/queue/week_mosaic_array.template
@@ -118,6 +118,17 @@ else
 fi
 
 $aprun BANE.py --cores=${ncpus} --noclobber --compress ${week}_${freq}.fits
+if [[ ! -e ${week}_${freq}_bkg.fits ]]
+then
+    echo "BANE failed to run!"
+    echo "Trying again with a single core."
+    $aprun BANE.py --noclobber --compress --cores=1 ${week}_${freq}.fits
+    if [[ ! -e ${week}_${freq}_bkg.fits ]]
+    then
+        echo "BANE wouldn't run even with a single core!"
+        exit 1
+    fi
+fi
 
 # Run some blind source-finding so I can do other tasks
 if [[ ! -e ${week}_${freq}_comp.vot ]]
